"""Added status logging

Revision ID: 7e5d578572a8
Revises: 2b3c4d5e6f7g
Create Date: 2026-07-28 16:11:01.846776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e5d578572a8'
down_revision: Union[str, Sequence[str], None] = '2b3c4d5e6f7g'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('failure_reason', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('applied_at', sa.DateTime(), nullable=True))
    op.alter_column('jobs', 'is_spam',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('weekly_reports', 'total_applications',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('weekly_reports', 'successful_applications',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weekly_reports', 'successful_applications',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('weekly_reports', 'total_applications',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jobs', 'is_spam',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('applications', 'applied_at')
    op.drop_column('applications', 'failure_reason')
    # ### end Alembic commands ###
